/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Assert;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testAnalyzingWeatherData() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String results = Library.analyzingWeatherData(weeklyMonthTemperatures);
        assertEquals(new String[]{"Low: 51 High: 72"});
    }

    private void assertEquals(String[] strings) {
    }

    @Test
    public void testTally() {
        List<String> votes = new ArrayList<>();
        votes.add("One");
        votes.add("Two");
        votes.add("Fourteen");
        votes.add("Three");
        votes.add("Seven");
        votes.add("Six");
        votes.add("Seven");
        votes.add("Forty-five");
        votes.add("eight");
        votes.add("Nineteen");

        String results = Library.tally(votes);

        Assert.assertEquals("seven", true, results);

        assertTrue(1 == results.length());

        //assertFalse(results = String.valueOf(7));


    }


}
