/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {

    //this test creates a new restaurant using the class and test values, and then compares the expected stringified result
    //with the actual.
    @Test
    public void testRestaurantToString() {
        //create new restaurant;
        Restaurant test = new Restaurant();
        //set name
        test.name = "test";
        //set number of stars
        test.stars = 4;
        //set price
        test.price = 5;

        //the .toString method adds *'s and $'s to an array list for each iteration through a for loop, counting up to
        // the int of stars or price respectively. Given that knowledge, this how we would expect it to print the test
        //restaurant.
        assertEquals("test [*, *, *, *] [$, $, $, $, $]", test.toString());
    }

    @Test
    public void testReviewToString() {
        Review test = new Review();
        test.body = "testing";
        test.author = "name of author";
        test.stars = 4;

        //the .toString method adds *'s and $'s to an array list for each iteration through a for loop, counting up to
        // the int of stars. Given that knowledge, this how we would expect it to print the test review.
        assertEquals("testing name of author [*, *, *, *]", test.toString());
    }
}

