/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

import javax.swing.border.TitledBorder;
import java.lang.reflect.Array;
import java.util.ArrayList;

import static org.junit.Assert.*;

public class ReviewsLibraryTest {

    //this test creates a new restaurant using the class and test values, and then compares the expected stringified result
    //with the actual.
    @Test
    public void testRestaurantToString() {
        //create new restaurant;
        Restaurant test = new Restaurant();
        //set name
        test.name = "test";
        //set number of stars
        test.stars = 4;
        //set price
        test.price = 5;

        //the .toString method adds *'s and $'s to an array list for each iteration through a for loop, counting up to
        // the int of stars or price respectively. Given that knowledge, this how we would expect it to print the test
        //restaurant.
        assertEquals("test [*, *, *, *] [$, $, $, $, $]", test.toString());
    }

    @Test
    public void testReviewToString() {
        Review test = new Review();
        test.body = "testing";
        test.author = "name of author";
        test.stars = 4;

        //the .toString method adds *'s and $'s to an array list for each iteration through a for loop, counting up to
        // the int of stars. Given that knowledge, this how we would expect it to print the test review.
        assertEquals("testing name of author [*, *, *, *]", test.toString());
    }

    @Test
    public void testEachBusinessAddReviews() {
        Shop testShop = new Shop();
        testShop.addReview("Info on the Shop", "Shop Patron", 2);

        String expectedShop = "null " + "Info on the Shop " + "Shop Patron " + "[*, *]";

        Restaurant testRestaurant = new Restaurant();
        testRestaurant.addReview("Info on the Restaurant", "Restaurant Patron", 2);

        String expectedRestaurant = "null " + "Info on the Restaurant " + "Restaurant Patron " + "[*, *]";

        Theater testTheater = new Theater();
        testTheater.addReview("Info on the Theater", "Theater Patron", 2, "Movie viewed");

        //this is what came out when I hand varified theater, unsure why movie is not attached.
        String expectedTheater = "null " + "Info on the Theater " + "Theater Patron " + "[*, *]";

        assertEquals(expectedShop, testShop.reviews.get(0).toString());
        assertEquals(expectedRestaurant, testRestaurant.reviews.get(0).toString());
        assertEquals(expectedTheater, testTheater.reviews.get(0).toString());
    }

}
